export const REMOVE_ALL_VIDEOS = "REMOVE_ALL_VIDEOS";
export const ADD_VIDEOS = "ADD_VIDEOS";

export const SET_VIDEOS_DIRECTORY = "SET_VIDEOS_DIRECTORY";
export const SET_VIDEO_URL = "SET_VIDEO_URL";
export const SET_VIDEO_TYPE = "SET_VIDEO_TYPE";
export const SET_VIDEO_FORMAT = "SET_VIDEO_FORMAT";
export const SET_VIDEO_QUALITY = "SET_VIDEO_QUALITY";

export const SET_FETCHED_VIDEOS = "SET_FETCHED_VIDEOS";

export const SET_VIDEOS = "SET_VIDEOS";
export const REMOVE_VIDEO = "REMOVE_VIDEO";

export const VIDEO_PROGRESS = "VIDEO_PROGRESS";
export const VIDEO_COMPLETE = "VIDEO_COMPLETE";
export const START_DOWNLOAD = "START_DOWNLOAD";

export const SET_AVAILABLE_VIDEO_FORMAT = "SET_AVAILABLE_VIDEO_FORMAT";
export const SET_AVAILABLE_VIDEO_QUALITY = "SET_AVAILABLE_VIDEO_QUALITY";
